### ISSUE TITLE
Deadline is 24 Hours

### ISSUE THREAD

**Issue by MattCSmith** [zeroDevs/FullstackTrends_Challenge-13#200]
# The Time Has Come!

Unfortunately the end of the month is approaching and a deadline needs to be set for finish of this project.  We are looking to freeze the project in approximately 24 hours or so. This will enable us to check the code thoroughly and fix anything that may need fixing ready for it to be listed on producthunt.com

If you could confirm if a PR for the issue you are working on is likely to be made by then or if you some extra time/help, that would be awesome.

**Comment by mortenkos** [comment]
@MattCSmith  are all the bugs removed or need some help with anything?

**Comment by MattCSmith** [comment]
I think we are pretty much upto date thanks @mortenkos

**Comment by mortenkos** [comment]
In case you haven't noticed this bug in mobile view. @MattCSmith  @The24thDS  @mikeattara 
Let's make it perfect before ProductHunt :)

![screenshot_20190130-120835](https://user-images.githubusercontent.com/25040343/51974299-4f885e00-2488-11e9-90ff-8ab4f688a55b.png)
![screenshot_20190130-120819](https://user-images.githubusercontent.com/25040343/51974308-53b47b80-2488-11e9-8ca7-bf05d6418ac2.png)

**Comment by The24thDS** [comment]
Should be addressed in #260

**Comment by mikeattara** [comment]
@MattCSmith Hope the project will be launched on Producthunt today.

**Comment by rahmot** [comment]
Hi @MattCSmith I'm sorry this is coming late. Thanks for the pdf document, it really helps. I have working on it but was having network problem. Currently, I'm on it but git status is displaying "permission denied". please help. Thanks

**Comment by MattCSmith** [comment]
Hey @rahmot,
I would guess the problem you are having is because your not pushing to your fork, instead I would imagine you are try to push to the main repo. You can confirm this by running: `git remote -v` 

IF the result returns two links that do not contain your github username, you will need to change this, before proceeding. Assuming your using https authentication the command you will need to run is:
`git remote set-url origin https://github.com/rahmot/coding_challenge-13.git`

**Comment by rahmot** [comment]
@MattCSmith Okay, Thanks

**Comment by rahmot** [comment]
@MattCSmith
The "git remote -v" displayed two links that contained my username with "fetch" and "push" in front of each respectively. 

I entered git status but still displayed "permission denied".

Thanks

**Comment by MattCSmith** [comment]
@rahmot Hey, did you configure your github credentials?
https://help.github.com/articles/setting-your-commit-email-address-in-git/

**Comment by mortenkos** [comment]
One thing that doesn't look nice on mobile, if you open the menu and scroll. menu background disappears.  @aneagoie 

![screenshot_20190131-173910](https://user-images.githubusercontent.com/25040343/52065717-c5bbbc00-257f-11e9-8c04-c393ba56c1ff.png)
![screenshot_20190131-174054](https://user-images.githubusercontent.com/25040343/52065728-ca807000-257f-11e9-9cf3-b7053aae7bb3.png)

**Comment by aneagoie** [comment]
Found a little bug. If anyone wants to fix it, it is fairly simple: The bottom logo "Full Stack Trends" returns a 404 when you click on it.

**Comment by mikeattara** [comment]
@aneagoie I tried fixing the bug #263

**Comment by aneagoie** [comment]
@mikeattara well done!

Ok, a bit of an issue.  I just deployed the latest to fullstacktrends.com

It looks like the zoom feature isn't working. Does anybody want to take a stab at it, or know if this feature was working fine before?

By the way we are releasing this tomorrow to producthunt!
